// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Auto":                                                 {"en": "Auto",                                                  "de": "Auto"},
    "Manual":                                               {"en": "Manual",                                                "de": "Manuell"},
    "settings":                                             {"en": "Nuki adapter settings",                                 "de": "Nuki Adaptereinstellungen"},
    "name":                                                 {"en": "Name of the Nuki bridge",                               "de": "Name der Nuki Bridge"},
    "ip":                                                   {"en": "IP address of the Nuki bridge",                         "de": "IP-Adresse der Nuki Bridge"},
    "ipeg":                                                 {"en": "e.g. 192.168.1.50",                                     "de": "z.B. 192.168.1.50"},
    "nuki_port":                                            {"en": "Port of the Nuki bridge",                               "de": "Port der Nuki Bridge"},
    "token":                                                {"en": "Token",                                                 "de": "Token"},
    "autoupd":                                              {"en": "Periodic state updates",                                "de": "Periodische Statusaktualisierungen"},
    "interval":                                             {"en": "Update interval (in minutes)",                          "de": "Aktualisierungsintervall (in Minuten)"},
    "host_cb":                                              {"en": "Use Callback",                                          "de": "Benutze Callback"},
    "host_port":                                            {"en": "Callback port in ioBroker",                             "de": "Callback-Port in ioBroker"},
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately",  "de": "Beim Speichern der Einstellungen wird der Adapter sofort neu gestartet."}
};