// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Auto":                                                 {"en": "Auto",                                                  "de": "Auto"},
    "Manual":                                               {"en": "Manual",                                                "de": "Manual"},
    "Nuki adapter settings":                                {"en": "Nuki adapter settings",                                 "de": "Nuki Adaptereinstellungen"},
    "Name of the Nuki bridge":                              {"en": "Name of the Nuki bridge",                               "de": "Name der Nuki bridge"},
    "Nuki bridge IP":                                       {"en": "IP adress of the Nuki Bridge",                          "de": "IP-Adresse der Nuki Bridge"},
    "Nuki bridge port":                                     {"en": "Port of the Nuki Bridge",                               "de": "Port der Nuki Bridge"},
    "Token":                                                {"en": "Token",                                                 "de": "Token"},
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately",  "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet."}
};